/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import menuCrud.pegawai;





public class Crudpegawai extends javax.swing.JFrame {
        pegawai Pegawai;
    
        
    public Crudpegawai() {
        initComponents();
        Pegawai = new pegawai (this);
        Pegawai.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtjabatan = new javax.swing.JTextField();
        txtalamatpegawai = new javax.swing.JTextField();
        txtnamapegawai = new javax.swing.JTextField();
        txtidpegawai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelModelPegawai = new javax.swing.JTable();
        btntambahpegawai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnupdatepegawai = new javax.swing.JButton();
        btnhapuspegawai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCariPegawai = new javax.swing.JTextField();
        btncaripegawai = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        txtjabatan.setBackground(new java.awt.Color(204, 153, 0));

        txtalamatpegawai.setBackground(new java.awt.Color(204, 153, 0));

        txtnamapegawai.setBackground(new java.awt.Color(204, 153, 0));

        txtidpegawai.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setText("CRUD PEGAWAI PADA MENU ADMIN");

        TabelModelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pegawai", "Nama Pegawai", "Alamat Pegawai", "Jabatan"
            }
        ));
        TabelModelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelModelPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelModelPegawai);

        btntambahpegawai.setText("Tambah");
        btntambahpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahpegawaiActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Pegawai");

        jLabel3.setText("Nama Pegawai");

        jLabel4.setText("Alamat Pegawai");

        jLabel5.setText("Jabatan");

        btnupdatepegawai.setText("Update");
        btnupdatepegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatepegawaiActionPerformed(evt);
            }
        });

        btnhapuspegawai.setText("Hapus");
        btnhapuspegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapuspegawaiActionPerformed(evt);
            }
        });

        jLabel6.setText("Cari");

        btncaripegawai.setText("CARI");
        btncaripegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripegawaiActionPerformed(evt);
            }
        });

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalamatpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnkembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncaripegawai)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btntambahpegawai)
                        .addGap(47, 47, 47)
                        .addComponent(btnupdatepegawai)
                        .addGap(29, 29, 29)
                        .addComponent(btnhapuspegawai)
                        .addGap(120, 120, 120))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamapegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtalamatpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambahpegawai)
                    .addComponent(btnupdatepegawai)
                    .addComponent(btnhapuspegawai))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCariPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncaripegawai)
                    .addComponent(btnkembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
       adminMenu am = new adminMenu ();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btntambahpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahpegawaiActionPerformed
        Pegawai.insert();
        Pegawai.isiTable();
        Pegawai.reset();
    }//GEN-LAST:event_btntambahpegawaiActionPerformed

    private void btnupdatepegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatepegawaiActionPerformed
        Pegawai.update();
        Pegawai.isiTable();
        Pegawai.reset();
    }//GEN-LAST:event_btnupdatepegawaiActionPerformed

    private void btnhapuspegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapuspegawaiActionPerformed
        Pegawai.delete();
        Pegawai.isiTable();
        Pegawai.reset();
    }//GEN-LAST:event_btnhapuspegawaiActionPerformed

    private void btncaripegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripegawaiActionPerformed
        Pegawai.cariNama();
    }//GEN-LAST:event_btncaripegawaiActionPerformed

    private void TabelModelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelModelPegawaiMouseClicked
        Pegawai.isiField(TabelModelPegawai.getSelectedRow());
    }//GEN-LAST:event_TabelModelPegawaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crudpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crudpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crudpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crudpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crudpegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelModelPegawai;
    private javax.swing.JButton btncaripegawai;
    private javax.swing.JButton btnhapuspegawai;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntambahpegawai;
    private javax.swing.JButton btnupdatepegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariPegawai;
    private javax.swing.JTextField txtalamatpegawai;
    private javax.swing.JTextField txtidpegawai;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnamapegawai;
    // End of variables declaration//GEN-END:variables

    public JButton getBtncaripegawai() {
        return btncaripegawai;
    }

    public void setBtncaripegawai(JButton btncaripegawai) {
        this.btncaripegawai = btncaripegawai;
    }

    public JButton getBtnhapuspegawai() {
        return btnhapuspegawai;
    }

    public void setBtnhapuspegawai(JButton btnhapuspegawai) {
        this.btnhapuspegawai = btnhapuspegawai;
    }

    public JButton getBtnkembali() {
        return btnkembali;
    }

    public void setBtnkembali(JButton btnkembali) {
        this.btnkembali = btnkembali;
    }

    public JButton getBtntambahpegawai() {
        return btntambahpegawai;
    }

    public void setBtntambahpegawai(JButton btntambahpegawai) {
        this.btntambahpegawai = btntambahpegawai;
    }

    public JButton getBtnupdatepegawai() {
        return btnupdatepegawai;
    }

    public void setBtnupdatepegawai(JButton btnupdatepegawai) {
        this.btnupdatepegawai = btnupdatepegawai;
    }

    public JTextField getTxtalamatpegawai() {
        return txtalamatpegawai;
    }

    public void setTxtalamatpegawai(JTextField txtalamatpegawai) {
        this.txtalamatpegawai = txtalamatpegawai;
    }

    public JTextField getTxtidpegawai() {
        return txtidpegawai;
    }

    public void setTxtidpegawai(JTextField txtidpegawai) {
        this.txtidpegawai = txtidpegawai;
    }

    public JTextField getTxtjabatan() {
        return txtjabatan;
    }

    public void setTxtjabatan(JTextField txtjabatan) {
        this.txtjabatan = txtjabatan;
    }

    public JTextField getTxtnamapegawai() {
        return txtnamapegawai;
    }

    public void setTxtnamapegawai(JTextField txtnamapegawai) {
        this.txtnamapegawai = txtnamapegawai;
    }

    public JTable getTabelModelPegawai() {
        return TabelModelPegawai;
    }

    public JTextField getTxtCariPegawai() {
        return txtCariPegawai;
    }

    



}
